version: "3.9"
x-aws-vpc: "${VPC_ID}"
x-aws-loadbalancer: "${AWS_ALB}"
services:
  aline-user:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/user-microservice-rl:${IMAGE_TAG}
    restart: on-failure:3
    environment:
      - APP_PORT=8070
    env_file:
      - ./env-files/user.env
    ports:
      #- "8070:8070"
      - target: 8070
        x-aws-protocol: http
  aline-underwriter:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/underwriter-microservice-rl:${IMAGE_TAG}
    restart: on-failure:3
    environment:
      - APP_PORT=8071    
    env_file:
      - ./env-files/underwriter.env
    ports:
      #- "8071:8071"
      - target: 8071
        x-aws-protocol: http      
  aline-bank:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/bank-microservice-rl:${IMAGE_TAG}
    restart: on-failure:3
    environment:
      - APP_PORT=8083    
    env_file:
      - ./env-files/bank.env
    ports:
      #- "8083:8083"
      - target: 8083
        x-aws-protocol: http
  aline-transaction:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/transaction-microservice-rl:${IMAGE_TAG}
    restart: on-failure:3
    environment:
      - APP_PORT=8073    
    env_file:
      - ./env-files/transaction.env
    ports:
      #- "8073:8073"
      - target: 8073
        x-aws-protocol: http
  aline-gateway:
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gateway-rl:${IMAGE_TAG}
    restart: on-failure:3
    env_file:
      - ./env-files/gateway.env
    ports:
      #- "8080:8080"
      - target: 8080
        x-aws-protocol: http
x-aws-cloudformation:
  Resources:
    AlineuserService:
      Properties:
        ServiceName: AlineuserService
    AlinebankService:
      Properties:
        ServiceName: AlinebankService
    AlinetransactionService:
      Properties:
        ServiceName: AlinetransactionService
    AlineunderwriterService:
      Properties:
        ServiceName: AlineunderwriterService
    AlinegatewayService:
      Properties:
        ServiceName: AlinegatewayService
  # aline-admin:
  #   image: rickylopez/aline-frontend:admin
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - REACT_APP_API_BASEURL=http://host.docker.internal:8080
  #     - REACT_APP_TOKEN_NAME=RATN
  #     - EXTEND_ESLINT=true
  # aline-landing:
  #   image: rickylopez/aline-frontend:landing
  #   ports:
  #     - "4200:80"
  #   environment:
  #     - PORT=4200
  #     - REACT_APP_MEMBER_DASHBOARD_URL=http://host.docker.internal:3007
  #     - REACT_APP_API=http://host.docker.internal:8080/api
  # aline-member:
  #   image: rickylopez/aline-frontend:member
  #   ports:
  #     - "3007:80"
    