pipeline {
    
    agent any

    tools {
        terraform "Terraform1.1.7"
    }

    parameters {
        string(name: "AWS_REGION", defaultValue: "us-west-1", trim: true, description: "Parameter for AWS region.")
        booleanParam(name: "DESTROY", defaultValue: "false", description: "Parameter to determine whether to destroy terraform infrastructure or not.")
    }

    environment {
        AWS_ACCOUNT_ID = credentials('AWS_ACCOUNT_ID')
        AWS_ACCESS_KEY = credentials('AWS_ACCESS_KEY')
        AWS_SECRET_KEY = credentials('AWS_SECRET_KEY')
    }

    stages {

        stage("Initialize") {

            steps{

                withCredentials([file(credentialsId: 'New_TFVars', variable: 'TFVARS')]){
                    sh "ls"
                    sh "cp \$TFVARS terraform/terraform.tfvars"
                }

                sh "cd terraform && terraform init"

            }

        }

        stage("Plan") {

            when { expression { !params.DESTROY} }

            steps{
                sh 'cd terraform && terraform init && terraform plan -no-color -out=terrplan'
            }


        }

        stage("Apply") {

            when { expression { !params.DESTROY} }

            steps{
                sh 'cd terraform && terraform apply -no-color -auto-approve "terrplan" > "apply_result.txt"'
            }

        }

        stage("Destroy"){

            when { expression { params.DESTROY} }

            steps {
                sh 'cd terraform && terraform destroy -no-color -auto-approve'
            }
        }


    }

    post {

        cleanup {
            sh "rm terraform/terraform.tfvars"
        }


    }

}