pipeline {
    
    agent any

    tools {
        terraform "Terraform1.1.7"
    }

    parameters {

        string(name: "AWS_REGION", defaultValue: "us-west-1", trim: true, description: "Parameter for AWS region.")
        booleanParam(name: "DESTROY", defaultValue: "false", description: "paramter to determine whether to destroy terraform infrastructure or not.")

    }

    environment {
        AWS_ACCOUNT_ID = credentials('AWS_ACCOUNT_ID')
        AWS_ACCESS_KEY = credentials('AWS_ACCESS_KEY')
        AWS_SECRET_KEY = credentials('AWS_SECRET_KEY')
    }

    stages {

        stage("Plan") {

            when { expression { !params.DESTROY} }

            steps{

                withCredentials([file(credentialsId: 'TFVars', variable: 'terraform.tfvars')]){

                    sh "cp \$terraform.tfvars /terraform/EKS/terraform.tfvars"

                }

                sh 'cd terraform/EKS && terraform plan -out=terrplan'

            }


        }

        stage("Apply") {

            when { expression { !params.DESTROY} }

            steps{

                sh 'cd terraform/EKS && terraform apply -auto-approve "terrplan" > "apply_${BUILD_ID}.txt"'

            }

        }

        stage("Destroy"){

            when { expression { !params.DESTROY} }

            steps {

                sh 'cd terraform/EKS && terraform destroy -force'

            }
        }

    }

}