#gateway app config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway 
  template:
    metadata:
      labels:
        app: gateway
        role: gateway
    spec:
      containers:
        - name: gateway
          image: $GATEWAY_IMAGE
          imagePullPolicy: Always
          ports:
             - containerPort: 8080
          envFrom:
          - configMapRef:
              name: gateway-configmap
          - secretRef:
              name: aline-secret
