---
- name: provisioning EC2 instances using Ansible
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    keypair: RickyLopez
    instance_type: t2.micro
    image: ami-0c02fb55956c7d316
    wait: yes
    region: us-west-1

  tasks:

    - name: Create EC2 Instance.
      block:
        - name: Launch bastion host.
          ec2:
            region: {{ region }}
            key_name: {{ keypair }}
            group: default
            instance_type: {{ instance_type }}
            image: {{ image }}
            wait: {{ wait }}
            wait_timeout: 500
            count: 1
            instance_tags:
              name: RL-BastHost
            monitoring: yes
            vpc_subnet_id: {{ subnet }}
            assign_public_ip: yes
          register: ec2
          delegate_to: localhost

        - name: Add bastion to host group.
          add_host:
            hostname: "{{ item.public_ip }}"
            groupname: launched
          
        - name: Wait for SSH port to be available.
          local_action:
            module: wait_for
            host: "{{ item.public_ip }}"
            port: 22
            delay: 10
            timeout: 120
      
      # - name: Configure EC2 Instance.
      #   block: 
  

  