---
- name: provisioning EC2 bastion server using Ansible
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    keypair: RickyLopez
    instance_type: t2.micro
    image:  ami-04a50faf2a2ec1901
    wait: yes
    region: us-west-1
    subnet: subnet-0e5434ad06532d827
    group:
      - default
      - RL-BastHost-SG

  tasks:

    - name: Create EC2 Instance.
      block:
        - name: Launch bastion host.
          ec2:
            region: "{{ region }}" 
            key_name: "{{ keypair }}"
            group: "{{ group }}"
            instance_type: "{{ instance_type }}"
            image: "{{ image }}"
            wait: "{{ wait }}"
            wait_timeout: 500
            count: 1
            instance_tags:
              Name: RL-BastHost
            monitoring: yes
            vpc_subnet_id: "{{ subnet }}"
            assign_public_ip: yes
          register: ec2
          delegate_to: localhost

        - name: Add bastion to host group.
          add_host:
            hostname: "{{ ec2.instances[0].public_ip }}"
            groupname: launched
          
        - name: Wait for SSH port to be available.
          local_action:
            module: wait_for
            host: "{{ ec2.instances[0].public_ip }}"
            port: 22
            delay: 10
            timeout: 600
      tags: ['never', 'ec2-create']
      
    - name: Configure EC2 Instance.
      block: 
        - name: Install yum-utils.
          dnf:
            name: yum-utils
    
        - name: Add HashiCorp Linux repo.
          ansible.builtin.shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

        - name: Install Terraform.
          dnf:
            name: terraform

      tags: ['always', 'ec2-configure']
  

  