#transaction app config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    app: transaction-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-microservice 
  template:
    metadata:
      labels:
        app: transaction-microservice
        role: backend
    spec:
      containers:
        - name: transaction-microservice
          image: $TRANSACTION_IMAGE
          imagePullPolicy: Always
          ports:
            - name: transaction
              containerPort: 8070
          envFrom:
          - configMapRef:
              name: microservice-configmap
          - secretRef:
              name: aline-secret
