apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rl-aline
  region: us-west-1

vpc:
  id: "${VPC_ID}"
  subnets:
    private:
      us-west-1a:
        id: "${PRIV_SUBNET_2}"
      us-west-1c:
        id: "${PRIV_SUBNET_2}"
    public:
      us-west-1a:
        id: "${PUB_SUBNET_1}"
      us-west-1c:
        id: "${PUB_SUBNET_2}"

nodeGroups:
  - name: rl-node-group-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
