apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rl-aline
  region: us-west-1

vpc:
  id: "vpc-0f6804dd048a36d99"
  subnets:
    private:
      us-west-1a:
        id: "subnet-082d07aa57fb7951b"
      us-west-1c:
        id: "subnet-05950e55642c48687"
    public:
      us-west-1a:
        id: "subnet-0e5434ad06532d827"
      us-west-1c:
        id: "subnet-01ea4c0f541fbb1da"

nodeGroups:
  - name: rl-node-group-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
