apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    role: backend
  type: NodePort
  ports:
    - name: user
      protocol: TCP
      port: 8070
      targetPort: user
    - name: underwriter
      protocol: TCP
      port: 8071
      targetPort: underwriter
    - name: transaction
      protocol: TCP
      port: 8073
      targetPort: transaction
    - name: bank
      protocol: TCP
      port: 8083
      targetPort: bank
